name: Upload to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v3 # Updated to the latest version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      if: github.ref == 'refs/heads/main' && matrix.python-version == '3.12'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*
