from NetworkScanning.tcp_scanner import single_tcp_scan
from NetworkScanning.udp_scanner import single_udp_scan
from NetworkScanning.banner_grabber import grab_banner
from NetworkScanning.utils import set_default_interface